<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/25
 * Time: 15:31
 */

namespace frontend\components;


use yii\base\ActionFilter;

class ActionTimeFilter extends ActionFilter
{
    private $_time;
    public function beforeAction($action)
    {
        $this->_time=microtime(true);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function afterAction($action, $result)
    {
        $time = microtime(true)-$this->_time;
        \Yii::debug($action->uniqueId.' spent '.$time.' seconds');
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }
}