<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/25
 * Time: 15:42
 */

namespace frontend\components;


use yii\base\ActionFilter;

class ActionIpFilter extends ActionFilter
{
    public function beforeAction($action)
    {
        $ip = \Yii::$app->request->getUserIP();
        \Yii::debug('client ip is '.$ip);

        if($ip=='127.0.0.1'){

        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}