<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "mms".
 *
 * @property int $id
 * @property int $val
 * @property int $version
 */
class Mms extends \yii\db\ActiveRecord
{
    const DATA_CREATE ='create';
    const DATA_UPDATE = 'update';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mms';
    }


    public function fields()
    {
        $fields = parent::fields(); // TODO: Change the autogenerated stub
        return [
            'val'=>'值',
            'version'=>'版本',
        ];
    }

    public function scenarios()
    {
        $scenarios = parent::scenarios(); // TODO: Change the autogenerated stub
        $scenarios[self::DATA_CREATE]=['val'];
        $scenarios[self::DATA_UPDATE]=['val'];
        return $scenarios;
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['val'], 'required'],
            [['val', 'version'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'val' => 'Val',
            'version' => 'Version',
        ];
    }
    public function optimisticLock()
    {
        return 'version';
    }
}
